# Generated by Django 4.0.1 on 2022-03-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0016_alter_facility_info_kmhfltest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edited_facility_info',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.partners'),
        ),
    ]
