# Generated by Django 4.0.1 on 2022-03-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0017_alter_edited_facility_info_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization_stewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steward', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tel_no', models.IntegerField(blank=True, default=None, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.counties')),
            ],
        ),
    ]
