# Generated by Django 4.0.1 on 2022-03-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0018_organization_stewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='agency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.sdp_agencies'),
        ),
    ]
