# Generated by Django 4.0.1 on 2022-03-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0019_alter_partners_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_stewards',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.partners'),
        ),
    ]
