# Generated by Django 4.0.1 on 2022-03-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0021_edited_facility_info_date_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edited_facility_info',
            name='user_edited',
        ),
        migrations.AddField(
            model_name='edited_facility_info',
            name='user_edited_email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='edited_facility_info',
            name='user_edited_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='partners',
            name='organization_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
