# Generated by Django 4.0.1 on 2022-03-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0022_remove_edited_facility_info_user_edited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization_id', models.UUIDField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='partners',
            name='organization_id',
        ),
    ]
