# Generated by Django 4.0.1 on 2022-03-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0023_organizations_remove_partners_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='organization_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
