# Generated by Django 4.0.1 on 2022-03-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0024_alter_organizations_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='access_right',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
